name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: macOS (Swift 6.2)
    runs-on: macos-26
    timeout-minutes: 10
    strategy:
      matrix:
        xcode: ["26.0"]
        config: ["debug", "release"]
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run ${{ matrix.config }} tests
        run: swift test -c ${{ matrix.config }} --enable-all-traits
